Commit for issue#39
t0xic0der/sanctuary-zero pull request #83
Opened 2020-10-22 04:31 UTC by adhyay2000

Added the server-side validation.
If a client is new joinee,he can create a new chatroom by sending NEW command
or validate by CHKUSR command. The chatroom are generated at a single point,hence
the disperancy coming in earlier case is resolved.

2020-10-22 04:31 UTC, adhyay2000 commented
fix for issue #39.

2020-10-23 02:12 UTC, t0xic0der requested changes
A lot of changes hail from #84. Please look at the suggestions I have provided there and work accordingly.

2020-10-23 02:12 UTC, t0xic0der commented on cnew.py
> +websocket = None
Please avoid such cross-type object initialization as far as possible.

2020-10-23 02:12 UTC, t0xic0der commented on cnew.py
> +async def consumer_handler(cphrsuit, username, chatroom, servaddr):
The websocket object must be passed here as a parameter.

2020-10-23 02:12 UTC, t0xic0der commented on cnew.py
> +async def producer_handler(cphrsuit, username, chatroom, servaddr):
The websocket object must be passed here as a parameter.

2020-10-23 14:08 UTC, adhyay2000 commented
Hi, I have added my justification for using this way, there. Please look that and reply what I should do?

2020-10-24 05:11 UTC, closed without merging