Issue 23: Display public IP address
t0xic0der/sanctuary-zero pull request #85
Opened 2020-10-22 08:11 UTC by shivangswain

Added a method to fetch and display public IP address in the server verbose

Linked Issue: #23

2020-10-23 03:17 UTC, t0xic0der requested changes
Please take a look at the changes I have suggested.

2020-10-23 03:17 UTC, t0xic0der commented on main.py
> +from requests import get
`requests` is quite a heavy module to import for task as small as this. Also, we cannot just assume that the users have `curl` or `wget` binaries installed on their distribution which makes it a difficult point to discuss about.

2020-10-23 03:17 UTC, t0xic0der commented on main.py
> +    return get('https://api64.ipify.org').text
This does a great job in retrieving an IPv6 address as evidenced in the screenshot I have attached just below.

![image](https://user-images.githubusercontent.com/49605954/96952289-1b7e8780-150c-11eb-826b-632d6ff6d64d.png)

But when it comes to IPv4, it still ends up fetching the IPv6 address.

![image](https://user-images.githubusercontent.com/49605954/96952331-34873880-150c-11eb-89e6-b05bf6b8635a.png)

2020-10-23 03:17 UTC, t0xic0der commented on main.py
> -        print_formatted_text(HTML("[" + obtntime() + "] " + "<b>SNCTRYZERO</b> > <red><b>The server could not be started up</b></red>"))
Nice touch with the corrected message. :wink:

2020-10-29 13:00 UTC, t0xic0der commented
Any updates, @shivangswain?

2020-10-29 16:59 UTC, shivangswain commented
Yeah, changing the whole implementation to use urllib3. ETA: 30 mins.

2020-10-29 17:34 UTC, closed without merging