Improved IP address fetch & display
t0xic0der/sanctuary-zero pull request #87
Opened 2020-10-29 17:45 UTC by shivangswain

Added a simple & better method to fetch and display public IP address in the server verbose

Closes #23

2020-10-29 18:59 UTC, t0xic0der requested changes
You would want to make the lines L#117 and L#121, the part of the `ipaddress` function so as to avoid repeating the same parts of code. Also, please make use of a try-except block in the function to address the cases when the server providing those addresses is unreachable.

(Don't worry about the specificity of the exception. Just catch one and let the user know that the addresses could not be fetched.)

2020-10-29 18:59 UTC, t0xic0der commented on main.py
> +    return response.data.decode('UTF-8')
Nice work done with fetching distinct addresses.

2020-10-29 19:01 UTC, t0xic0der approved these changes

2020-10-29 19:01 UTC, t0xic0der commented on main.py
> +import asyncio, websockets, sys, click, urllib3, time
`urllib3` is a not-so elegant module but lightweight - something which is perfect for our usecase. Thanks for replacing `requests` in favour of this module.

2020-10-29 19:02 UTC, t0xic0der requested changes
Just make changes listed on https://github.com/t0xic0der/sanctuary-zero/pull/87#pullrequestreview-519979051.

2020-10-30 16:06 UTC, shivangswain commented
Just pushed a new, even simpler and faster implementation

2020-10-30 16:06 UTC, merged